name: einet_ccle
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - imageio=2.31.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1v
  - packaging=23.0
  - pandas=1.5.3
  - pcre=8.45
  - pip=23.1.2
  - ply=3.11
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - seaborn=0.12.2
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=2.0.2
  - torchmetrics=0.11.4
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.2
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.4
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - filelock==3.12.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - joblib==1.2.0
      - lit==16.0.5.post0
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - pathtools==0.1.2
      - pillow==9.5.0
      - protobuf==4.23.2
      - psutil==5.9.5
      - pyqt5-sip==12.11.0
      - pytorch-fid==0.3.0
      - pyyaml==6.0
      - requests==2.31.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - threadpoolctl==3.1.0
      - torch==2.0.0
      - tqdm==4.65.0
      - triton==2.0.0
      - urllib3==2.0.3
      - wandb==0.15.4
